services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-ci-app-prod
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/todos
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: ["pnpm", "start"]

  db:
    image: postgres:16
    container_name: devops-ci-db-prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todos"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data_prod:
